[package]
name = "example_fuzzer"
version = "0.1.0"
authors = ["Lain Dev"]
edition = "2018"

[dependencies]
lain = { version = "0.2", path = "../../lain" }
ctrlc = "3.1"
env_logger = "0.6.2"
log = "0.4"